name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
jobs:
  job_one:
    runs-on: ubuntu-latest
    name: run tests
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: '17'
      - name: yarn install, test and build
        run: |
          yarn
          yarn run test a --runInBand --coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3.1.0
